server:
  port: 9877


spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud-check/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


